# Generated by Django 5.2.4 on 2025-08-12 18:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseCode', models.CharField(max_length=10, unique=True)),
                ('CourseName', models.CharField(max_length=100)),
                ('Credit', models.DecimalField(decimal_places=2, max_digits=4)),
                ('EntryDate', models.DateField(default=django.utils.timezone.now)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Department.department')),
            ],
        ),
    ]
