# Generated by Django 5.2.4 on 2025-08-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='CourseCode',
            new_name='courseCode',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='CourseName',
            new_name='courseName',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Credit',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='EntryDate',
            new_name='entryDate',
        ),
    ]
