# Generated by Django 5.2.4 on 2025-08-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_rename_coursecode_course_coursecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='courseName',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
