# Generated by Django 5.2.4 on 2025-08-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='End',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='Start',
            new_name='start',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_marks',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_no',
            field=models.IntegerField(default=1),
        ),
    ]
