# Generated by Django 5.2.4 on 2025-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_rename_end_quiz_end_rename_start_quiz_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
