# Generated by Django 5.2.4 on 2025-08-10 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('UID', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=30)),
                ('Join_Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
