# Generated by Django 5.2.4 on 2025-08-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Join_Date',
            new_name='join_date',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Status',
            new_name='status',
        ),
    ]
