# Generated by Django 5.2.4 on 2025-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_rename_department_teacher_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='changeme123', max_length=128),
        ),
    ]
