# Generated by Django 5.2.4 on 2025-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_teacher_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='UID',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='teacher123', max_length=128),
        ),
    ]
