# Generated by Django 5.2.4 on 2025-08-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Start',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='Title',
            new_name='title',
        ),
        migrations.AddField(
            model_name='department',
            name='fullForm',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
