# Generated by Django 5.2.4 on 2025-08-12 18:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.IntegerField()),
                ('Division', models.CharField(max_length=1)),
                ('Title', models.CharField(max_length=10)),
                ('EntryDate', models.DateField(default=django.utils.timezone.now)),
                ('Complete', models.BooleanField(default=False)),
            ],
        ),
    ]
