# Generated by Django 5.2.4 on 2025-08-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='Batch',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='Division',
            new_name='division',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='EntryDate',
            new_name='entryDate',
        ),
        migrations.RenameField(
            model_name='batch',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='Complete',
        ),
        migrations.AddField(
            model_name='batch',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
