# Generated by Django 5.2.4 on 2025-08-10 17:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('UID', models.IntegerField(max_length=11, unique=True)),
                ('Department', models.CharField(max_length=10)),
                ('Batch', models.CharField(max_length=3)),
                ('Admission_Date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
