# Generated by Django 5.2.4 on 2025-08-13 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Admission_Date',
            new_name='admission_date',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Batch',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Roll',
            new_name='roll',
        ),
    ]
