# Generated by Django 5.2.4 on 2025-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_rename_admission_date_student_admission_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
        migrations.AlterField(
            model_name='student',
            name='UID',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
