# Generated by Django 5.2.4 on 2025-08-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_remove_student_roll_alter_student_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='UID',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='student123'),
        ),
    ]
