# Generated by Django 5.2.4 on 2025-08-18 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quiz', '0002_rename_end_quiz_end_rename_start_quiz_start_and_more'),
        ('Student', '0004_rename_uid_student_uid_student_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.JSONField()),
                ('submission_on', models.DateField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False)),
                ('marks', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
            options={
                'unique_together': {('quiz', 'student')},
            },
        ),
    ]
